### ISSUE TITLE
Action失败

### ISSUE THREAD

**Issue by ccoz** [GuangzheJiang/rss_everyday#1]
go: downloading github.com/mmcdole/goxpp v0.0.0-20181012175147-0068e33feabf
go: downloading github.com/technoweenie/multipartstreamer v1.0.1
go: downloading github.com/PuerkitoBio/goquery v1.5.1
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/andybalholm/cascadia v1.1.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73df59]

goroutine 1 [running]:
main.GetPostInfo(0xc000032ad0, 0xc, 0xc000026680, 0x38, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/rss_everyday/rss_everyday/main.go:80 +0x539
main.GetPosts()
	/home/runner/work/rss_everyday/rss_everyday/main.go:63 +0xe6
main.main()
	/home/runner/work/rss_everyday/rss_everyday/main.go:105 +0x25
exit status 2
net/http: server replied with more than declared Content-Length; truncated
Error: Process completed with exit code 1.

**Comment by dianbanjiu** [comment]
这个程序会解析 rss 中的更新时间，根据更新时间进行判断是否可以推送，如果你有某些 rss 链接解析不出这个字段，就会出现这种情况，不过你可以使用最新的代码，最新的代码即使解析不出这个字段也不会导致整个 action 失败。
