### ISSUE TITLE
可以支持下群聊的发送么

### ISSUE THREAD

**Issue by Dreamer-Paul** [GuangzheJiang/rss_everyday#2]
正常部署上项目，Actions 也成功运行了，但是机器人并没有成功发送出消息，且没有任何报错信息。检查过两个变量的值，GroupID 我用 `getUpdates` 这个 API 获取的，使用机器人 Token 也可以通过 sendMessage 这个 API 发送消息，会是什么原因导致的？希望作者能提供下排除建议...

另外，RSS 地址是 https://paul.ren/feed 和 https://paugram.com/feed 会是数据问题么？

再次看了一下 README，是不支持「群聊」只能是「Channel」么？

**Comment by dianbanjiu** [comment]
是的，现在只支持 Channel。群聊我后面看看能否实现

**Comment by dianbanjiu** [comment]
我今天尝试了一下，其实即便是群组也可以正常工作的。群组 id 可以通过 web 端直接获取，点击群组之后 url 显示类似https://web.telegram.org/#/im?p=gxxx，你只需要把 channelid 替换为 -xxx 即可
